-- Seed data for 'exercises' table
TRUNCATE TABLE "exercises" RESTART IDENTITY CASCADE;

INSERT INTO "exercises" ("id", "name", "primaryMuscle", "secondaryMuscle", "mechanics", "userId", "bodyRegion") VALUES
('ex-1', 'Barbell Bench Press', 'Chest', 'Triceps', 'Compound', NULL, NULL),
('ex-2', 'Incline Barbell Bench Press', 'Chest', 'Shoulders', 'Compound', NULL, NULL),
('ex-3', 'Decline Barbell Bench Press', 'Chest', 'Triceps', 'Compound', NULL, NULL),
('ex-4', 'Dumbbell Bench Press', 'Chest', 'Triceps', 'Compound', NULL, NULL),
('ex-5', 'Incline Dumbbell Bench Press', 'Chest', 'Shoulders', 'Compound', NULL, NULL),
('ex-6', 'Dumbbell Flyes', 'Chest', NULL, 'Isolation', NULL, NULL),
('ex-7', 'Incline Dumbbell Flyes', 'Chest', NULL, 'Isolation', NULL, NULL),
('ex-8', 'Cable Crossover', 'Chest', NULL, 'Isolation', NULL, NULL),
('ex-9', 'Chest Dips', 'Chest', 'Triceps', 'Compound', NULL, NULL),
('ex-10', 'Machine Chest Press', 'Chest', 'Triceps', 'Compound', NULL, NULL),
('ex-11', 'Pec Deck', 'Chest', NULL, 'Isolation', NULL, NULL),
('ex-12', 'Push-Ups', 'Chest', 'Triceps', 'Compound', NULL, NULL),
('ex-13', 'Barbell Row', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-14', 'Dumbbell Row', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-15', 'Pendlay Row', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-16', 'T-Bar Row', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-17', 'Seated Cable Row', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-18', 'Lat Pulldown', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-19', 'Pull-Ups', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-20', 'Chin-Ups', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-21', 'Deadlift', 'Back', 'Hamstrings', 'Compound', NULL, NULL),
('ex-22', 'Rack Pull', 'Back', 'Traps', 'Compound', NULL, NULL),
('ex-23', 'Straight Arm Pulldown', 'Back', NULL, 'Isolation', NULL, NULL),
('ex-24', 'Machine Row', 'Back', 'Biceps', 'Compound', NULL, NULL),
('ex-25', 'Overhead Press', 'Shoulders', 'Triceps', 'Compound', NULL, NULL),
('ex-26', 'Dumbbell Shoulder Press', 'Shoulders', 'Triceps', 'Compound', NULL, NULL),
('ex-27', 'Arnold Press', 'Shoulders', 'Triceps', 'Compound', NULL, NULL),
('ex-28', 'Lateral Raise', 'Shoulders', NULL, 'Isolation', NULL, NULL),
('ex-29', 'Cable Lateral Raise', 'Shoulders', NULL, 'Isolation', NULL, NULL),
('ex-30', 'Front Raise', 'Shoulders', NULL, 'Isolation', NULL, NULL),
('ex-31', 'Reverse Pec Deck', 'Shoulders', NULL, 'Isolation', NULL, NULL),
('ex-32', 'Face Pull', 'Shoulders', 'Traps', 'Compound', NULL, NULL),
('ex-33', 'Upright Row', 'Shoulders', 'Traps', 'Compound', NULL, NULL),
('ex-34', 'Machine Shoulder Press', 'Shoulders', 'Triceps', 'Compound', NULL, NULL),
('ex-35', 'Barbell Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-36', 'EZ-Bar Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-37', 'Dumbbell Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-38', 'Hammer Curl', 'Biceps', 'Forearms', 'Isolation', NULL, NULL),
('ex-39', 'Incline Dumbbell Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-40', 'Preacher Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-41', 'Concentration Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-42', 'Cable Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-43', 'Spider Curl', 'Biceps', NULL, 'Isolation', NULL, NULL),
('ex-44', 'Reverse Curl', 'Biceps', 'Forearms', 'Isolation', NULL, NULL),
('ex-45', 'Tricep Pushdown', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-46', 'Overhead Tricep Extension', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-47', 'Skull Crushers', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-48', 'Close-Grip Bench Press', 'Triceps', 'Chest', 'Compound', NULL, NULL),
('ex-49', 'Tricep Dips', 'Triceps', 'Chest', 'Compound', NULL, NULL),
('ex-50', 'Tricep Kickback', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-51', 'Cable Overhead Extension', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-52', 'Diamond Push-Ups', 'Triceps', 'Chest', 'Compound', NULL, NULL),
('ex-53', 'Rope Pushdown', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-54', 'Single-Arm Pushdown', 'Triceps', NULL, 'Isolation', NULL, NULL),
('ex-55', 'Barbell Squat', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-56', 'Front Squat', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-57', 'Leg Press', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-58', 'Hack Squat', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-59', 'Leg Extension', 'Quadriceps', NULL, 'Isolation', NULL, NULL),
('ex-60', 'Bulgarian Split Squat', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-61', 'Walking Lunges', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-62', 'Goblet Squat', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-63', 'Sissy Squat', 'Quadriceps', NULL, 'Isolation', NULL, NULL),
('ex-64', 'Smith Machine Squat', 'Quadriceps', 'Glutes', 'Compound', NULL, NULL),
('ex-65', 'Romanian Deadlift', 'Hamstrings', 'Glutes', 'Compound', NULL, NULL),
('ex-66', 'Stiff-Leg Deadlift', 'Hamstrings', 'Glutes', 'Compound', NULL, NULL),
('ex-67', 'Lying Leg Curl', 'Hamstrings', NULL, 'Isolation', NULL, NULL),
('ex-68', 'Seated Leg Curl', 'Hamstrings', NULL, 'Isolation', NULL, NULL),
('ex-69', 'Good Morning', 'Hamstrings', 'Back', 'Compound', NULL, NULL),
('ex-70', 'Dumbbell Romanian Deadlift', 'Hamstrings', 'Glutes', 'Compound', NULL, NULL),
('ex-71', 'Nordic Hamstring Curl', 'Hamstrings', NULL, 'Isolation', NULL, NULL),
('ex-72', 'Glute-Ham Raise', 'Hamstrings', 'Glutes', 'Compound', NULL, NULL),
('ex-73', 'Single-Leg Deadlift', 'Hamstrings', 'Glutes', 'Compound', NULL, NULL),
('ex-74', 'Cable Pull-Through', 'Hamstrings', 'Glutes', 'Compound', NULL, NULL),
('ex-75', 'Hip Thrust', 'Glutes', 'Hamstrings', 'Compound', NULL, NULL),
('ex-76', 'Barbell Hip Thrust', 'Glutes', 'Hamstrings', 'Compound', NULL, NULL),
('ex-77', 'Glute Bridge', 'Glutes', NULL, 'Isolation', NULL, NULL),
('ex-78', 'Cable Kickback', 'Glutes', NULL, 'Isolation', NULL, NULL),
('ex-79', 'Sumo Deadlift', 'Glutes', 'Hamstrings', 'Compound', NULL, NULL),
('ex-80', 'Step-Ups', 'Glutes', 'Quadriceps', 'Compound', NULL, NULL),
('ex-81', 'Reverse Lunge', 'Glutes', 'Quadriceps', 'Compound', NULL, NULL),
('ex-82', 'Smith Machine Hip Thrust', 'Glutes', 'Hamstrings', 'Compound', NULL, NULL),
('ex-83', 'Single-Leg Hip Thrust', 'Glutes', NULL, 'Isolation', NULL, NULL),
('ex-84', 'Abduction Machine', 'Glutes', NULL, 'Isolation', NULL, NULL),
('ex-85', 'Standing Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-86', 'Seated Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-87', 'Leg Press Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-88', 'Smith Machine Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-89', 'Donkey Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-90', 'Single-Leg Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-91', 'Barbell Calf Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-92', 'Tibialis Raise', 'Calves', NULL, 'Isolation', NULL, NULL),
('ex-93', 'Crunches', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-94', 'Hanging Leg Raise', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-95', 'Cable Crunch', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-96', 'Ab Wheel Rollout', 'Abs', NULL, 'Compound', NULL, NULL),
('ex-97', 'Plank', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-98', 'Russian Twist', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-99', 'Leg Raise', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-100', 'Decline Sit-Up', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-101', 'Mountain Climbers', 'Abs', NULL, 'Compound', NULL, NULL),
('ex-102', 'Bicycle Crunch', 'Abs', NULL, 'Isolation', NULL, NULL),
('ex-103', 'Barbell Shrug', 'Traps', NULL, 'Isolation', NULL, NULL),
('ex-104', 'Dumbbell Shrug', 'Traps', NULL, 'Isolation', NULL, NULL),
('ex-105', 'Farmer''s Walk', 'Traps', 'Forearms', 'Compound', NULL, NULL),
('ex-106', 'Trap Bar Shrug', 'Traps', NULL, 'Isolation', NULL, NULL),
('ex-107', 'Cable Shrug', 'Traps', NULL, 'Isolation', NULL, NULL),
('ex-108', 'Behind-the-Back Shrug', 'Traps', NULL, 'Isolation', NULL, NULL),
('ex-109', 'Smith Machine Shrug', 'Traps', NULL, 'Isolation', NULL, NULL),
('ex-110', 'Overhead Shrug', 'Traps', 'Shoulders', 'Isolation', NULL, NULL),
('ex-111', 'Wrist Curl', 'Forearms', NULL, 'Isolation', NULL, NULL),
('ex-112', 'Reverse Wrist Curl', 'Forearms', NULL, 'Isolation', NULL, NULL),
('ex-113', 'Farmer''s Carry', 'Forearms', 'Traps', 'Compound', NULL, NULL),
('ex-114', 'Dead Hang', 'Forearms', NULL, 'Isolation', NULL, NULL),
('ex-115', 'Plate Pinch', 'Forearms', NULL, 'Isolation', NULL, NULL),
('ex-116', 'Behind-the-Back Wrist Curl', 'Forearms', NULL, 'Isolation', NULL, NULL),
('ex-117', 'Wrist Roller', 'Forearms', NULL, 'Isolation', NULL, NULL),
('ex-118', 'Grip Squeeze', 'Forearms', NULL, 'Isolation', NULL, NULL);
